# Generated by Django 2.1.7 on 2021-07-19 03:01

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('studentList', models.FileField(upload_to='studentlist', verbose_name='學生名單(學號+姓名)')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homeworkId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='標題', max_length=20, verbose_name='標題')),
                ('description', models.CharField(default='無描述', max_length=100, null=True, verbose_name='描述')),
                ('languageOption', multiselectfield.db.fields.MultiSelectField(choices=[('java', 'java'), ('py', 'python')], default='java', max_length=10, verbose_name='開放語言')),
                ('startDateTime', models.DateTimeField(verbose_name='開始時間')),
                ('endDateTime', models.DateTimeField(verbose_name='結束時間')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework_attachment/', verbose_name='附件')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problemId', models.AutoField(primary_key=True, serialize=False)),
                ('problemName', models.CharField(default=1, max_length=20, null=True, verbose_name='問題名稱')),
                ('timeout', models.IntegerField(default=5, verbose_name='限制時間')),
                ('sampleIn', models.FileField(null=True, upload_to='problem/', verbose_name='輸入測資')),
                ('sampleOut', models.FileField(null=True, upload_to='problem/', verbose_name='輸出測資')),
                ('homework', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Homework')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField(default=False, verbose_name='通過')),
                ('language', models.CharField(default='未選擇', max_length=25, verbose_name='使用語言')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='帳號')),
                ('studentName', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=100, verbose_name='密碼')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='course_student',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
    ]
