# Generated by Django 2.1.7 on 2021-07-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210719_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isFirstLogin',
            field=models.BooleanField(default=True),
        ),
    ]
